This sucessfully bootstraps (with some rough edges...)
Here, with this in place, we can bootstrap. Something about the
record_success() function is not working correctly as we report no
modified rows. I think we need to prefer exec_iter() which returns a
QueryResult rather than the short-hand funcitons which simply return an
Option<T>

The output from a quick fun run locally:

    *[wip-run-built-in-migrations][~/code/mitre]$ echo DROP DATABASE mitre | mysql -h 127.0.0.1 -u root -pexample

    *[wip-run-built-in-migrations][~/code/mitre]$ ./target/debug/mitre -c test/fixtures/example-1-simple-mixed-migrations/config.yml -d $(mktemp -d) up
    Template CTX is Map({"mariadb_migration_state_table_name": StrVal(mitre_migration_state), "mariadb_migration_state_databaes_name": StrVal(mitre)})
    Result Is: []
    thread 'main' panicked at 'affected no rows', src/mitre/runner/mariadb.rs:82:23
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    *[wip-run-built-in-migrations][~/code/mitre]$ mysql -h 127.0.0.1 -u root -pexample mitre
    Reading table information for completion of table and column names
    You can turn off this feature to get a quicker startup with -A

    Welcome to the MariaDB monitor.  Commands end with ; or \g.
    Your MariaDB connection id is 242
    Server version: 10.5.8-MariaDB-1:10.5.8+maria~focal mariadb.org binary distribution

    Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

    Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

    MariaDB [mitre]> SELECT * FROM mitre_migration_state;
    +---------------------+------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------+----------+-----------------+
    | version             | up   | down | change                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | applied_at_utc      | apply_time_sec | built_in | environment     |
    +---------------------+------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------+----------+-----------------+
    | 2020-12-16 20:20:20 | NULL | NULL | Template { ctx: Context { template_path: ".", template_extension: mustache }, tokens: [Text("-- Bootstrap the database\n--\n-- This does not include the stanza IF NOT EXISTS because we\n-- should never enter this path if the DB does already exist,\n-- this bootstrapping migration _must_ create the world.\nCREATE DATABASE "), EscapedTag(["mariadb_migration_state_databaes_name"], "{{mariadb_migration_state_databaes_name}}"), Text(" CHARACTER SET utf8 COLLATE utf8_bin;\n\n-- Use the newly created database\nUSE "), EscapedTag(["mariadb_migration_state_databaes_name"], "{{mariadb_migration_state_databaes_name}}"), Text(";\n\n-- Table name must agree with the constant in the mariadb.rs \nCREATE TABLE "), EscapedTag(["mariadb_migration_state_table_name"], "{{mariadb_migration_state_table_name}}"), Text(" (\n\n  -- TIMESTMAP is YYYYMMDDHHMMSS just like migration filenames\n  -- assumed to be UTC, and stored as such.\n  `version` TIMESTAMP NOT NULL PRIMARY KEY,\n\n  -- These columns store the up/down/change migrations, so we\n  -- know what was applied and can handle turning the database\n  -- back in a branch, for e.g by running \"downs\" in environments\n  -- that have had the code rolled-back, perhaps.\n  --\n  -- We don\'t store the parsed templating code, this is just here\n  -- for re-runs and a semblence of independence from code lifecycle\n  --\n  -- Backticks everywhere for consistency, required here \n  -- because `change` is a reserved word.\n  `up` BLOB,\n  `down` BLOB,\n  `change` BLOB,\n\n  -- Simple metadata columns\n  `applied_at_utc` TIMESTAMP NOT NULL,\n  `apply_time_sec` BIGINT UNSIGNED NOT NULL,\n\n  -- Was this a built-in migration\n  `built_in` BOOLEAN NOT NULL,\n\n  -- Environment\n  `environment` TINYTEXT NOT NULL\n\n) ENGINE=InnoDB;\n-- ENGINE=InnoDB is the default, but let\'s be explicit.\n")], partials: {} } | 2021-02-14 20:11:12 |              0 |        1 | NOT IMPLEMENTED |
    +---------------------+------+------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------+----------+-----------------+
    1 row in set (0.001 sec)

    MariaDB [mitre]> ^DBye

In other words, the bootstrap migation is run and remembered 🎉🎉🎉🎉🎉🎉🎉

Some problems to overcome:

 - Template did not serialize properly (I expect we catch this with
 tests when the time comes, and it may be easier to also keep the source
 string/str on the migration part than try and recover it from the
 mustache template)

 - Does not correctly track whether or not we inserted the rows
 correctly (see first paragraph), I think that will be easy to solve.

 - Very little error handling, but the cases are all fairly clear.

 - The up() loop behaviour isn't tested for, what if there's more than
 one migration?