Checkpoint Commit
At this point we're failing with this:

      error[E0277]: a value of type `(runner::MigrationResult, migrations::Migration)` cannot be built from an iterator over elements of type `(runner::MigrationResult, migrations::Migration)`
        --> src/engine.rs:59:12
         |
      59 |         }).collect::<MigrationResultTuple>().into_iter())
         |            ^^^^^^^ value of type `(runner::MigrationResult, migrations::Migration)` cannot be built from `std::iter::Iterator<Item=(runner::MigrationResult, migrations::Migration)>`
         |
         = help: the trait `FromIterator<(runner::MigrationResult, migrations::Migration)>` is not implemented for `(runner::MigrationResult, migrations::Migration)`

      error[E0599]: the method `into_iter` exists for tuple `(runner::MigrationResult, migrations::Migration)`, but its trait bounds were not satisfied
        --> src/engine.rs:59:46
         |
      59 |         }).collect::<MigrationResultTuple>().into_iter())
         |                                              ^^^^^^^^^ method cannot be called on `(runner::MigrationResult, migrations::Migration)` due to unsatisfied trait bounds
         |
         = note: the following trait bounds were not satisfied:
                 `(runner::MigrationResult, migrations::Migration): std::iter::Iterator`
                 which is required by `(runner::MigrationResult, migrations::Migration): IntoIterator`
                 `&(runner::MigrationResult, migrations::Migration): std::iter::Iterator`
                 which is required by `&(runner::MigrationResult, migrations::Migration): IntoIterator`
                 `&mut (runner::MigrationResult, migrations::Migration): std::iter::Iterator`
                 which is required by `&mut (runner::MigrationResult, migrations::Migration): IntoIterator`

      error: aborting due to 2 previous errors; 1 warning emitted

The error probably goes away if I use `fn foo<T: IntoIterator>(_: X) -> Result<(), ()>` rather than the IntoIter<T> I tried so far.